### ISSUE TITLE
creature_loot_template still has errors

### ISSUE THREAD

**Issue by apo126** [cmangos/wotlk-db#58]
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19984 item 24008: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19983 item 24008: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19982 item 24008: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19984 item 24010: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19983 item 24010: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19982 item 24010: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19984 item 24093: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19984 item 24000: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19983 item 24000: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19982 item 24000: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 20161 item 24035: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19984 item 24035: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19983 item 24035: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19982 item 24035: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 20161 item 24001: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19984 item 24092: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19984 item 24001: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19983 item 24001: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 20161 item 24005: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19984 item 24005: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19983 item 24005: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19982 item 24005: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 20161 item 24007: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19984 item 24007: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19983 item 24007: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19982 item 24007: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 20161 item 24002: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19984 item 24002: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19983 item 24002: negative chance is given for a reference, skipped
2017-01-14 09:17:43 Table 'creature_loot_template' entry 19982 item 24002: negative chance is given for a reference, skipped

**Comment by NeatElves** [comment]
/bGrz3s/b wrote
Pls run ./installFullDB.sh again
This issue was fixed in [720]
https://github.com/cmangos/wotlk-db/commit/3c42977e31bb98359f4e64c85b4378585fc0a210
or pls add this:
```code
UPDATE creature_loot_template SET ChanceOrQuestChance = -30 WHERE entry = 19982 AND item = 30655; -- adjust drop chances for quest item
UPDATE creature_loot_template SET ChanceOrQuestChance = -30 WHERE entry = 19983 AND item = 30655;
UPDATE creature_loot_template SET ChanceOrQuestChance = -25 WHERE entry = 19984 AND item = 30655;
UPDATE creature_loot_template SET ChanceOrQuestChance = -10 WHERE entry = 20161 AND item = 30655;
```

**Comment by Grz3s** [comment]
@apo126 
pls update your DB repo and then run ./installFullDB.sh 
Pls look at file 717_quest_10566.sql (has been modified in commit [720])
and new one look like:
``` sql
-- ===================
-- Fixes by Killerwife
-- ===================
-- Trial and error quest script
-- http://www.wowhead.com/quest=10566/trial-and-error

DELETE FROM item_loot_template WHERE entry = 30650; -- fix bag loot
INSERT INTO item_loot_template (entry,item,ChanceOrQuestChance,groupid,mincountOrRef,maxcount) VALUES
(30650,30651,100,1,1,1), -- Dertroks First Wand
(30650,30652,100,2,1,1), -- Dertroks Second Wand
(30650,30653,100,3,1,1), -- Dertroks Third Wand
(30650,30654,100,4,1,1); -- Dertroks Fourth Wand

UPDATE creature_loot_template SET ChanceOrQuestChance = -30 WHERE entry = 19982 AND item = 30655;  -- adjust drop chances for quest item
UPDATE creature_loot_template SET ChanceOrQuestChance = -30 WHERE entry = 19983 AND item = 30655;
UPDATE creature_loot_template SET ChanceOrQuestChance = -25 WHERE entry = 19984 AND item = 30655;
UPDATE creature_loot_template SET ChanceOrQuestChance = -10 WHERE entry = 20161 AND item = 30655;

UPDATE quest_template SET ReqSourceId1 = 30655,ReqSourceCount1 = 4 WHERE entry = 10566; -- make item drop during quest

DELETE FROM creature_template_spells WHERE entry = 21254;
INSERT INTO creature_template_spells (entry, spell1, spell2, spell3, spell4, spell5, spell6, spell7, spell8) VALUES
(21254,34802,0,0,0,0,0,0,0); -- add kick to ogre spell bar
```
Pls add it into your DB... and problem will be gone...
GL

**Comment by apo126** [comment]
@Grz3s 
After sourcing 717_quest_10566.sql, still have below errors:
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19984 item 24008: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19983 item 24008: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19982 item 24008: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19984 item 24010: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19983 item 24010: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19982 item 24010: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19984 item 24093: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19984 item 24000: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19983 item 24000: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19982 item 24000: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 20161 item 24035: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19984 item 24035: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19983 item 24035: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19982 item 24035: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 20161 item 24001: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19984 item 24092: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19984 item 24001: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19983 item 24001: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 20161 item 24005: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19984 item 24005: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19983 item 24005: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19982 item 24005: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 20161 item 24007: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19984 item 24007: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19983 item 24007: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19982 item 24007: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 20161 item 24002: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19984 item 24002: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19983 item 24002: negative chance is given for a reference, skipped
2017-01-21 15:46:29 Table 'creature_loot_template' entry 19982 item 24002: negative chance is given for a reference, skipped

**Comment by Grz3s** [comment]
yes because you added damaged 717 before... (our mistake) and now you have all listed here entrys damaged:
I'll say last time ...
PLS Run **./installFullDB.sh** again (it will fix your issue) .. you wont loose any game progres (characters table is not touch by this script)..
But if for any (not known) reason you still wont do that... than you need to fix loot for all listed above entrys manualy...
End of subject
